# Google App Engine Configuration (Alternative to GCE VM)
runtime: python39
entrypoint: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0

# Instance Class (Adjust as needed)
instance_class: F2

# Automatic Scaling
automatic_scaling:
  min_instances: 0
  max_instances: 1

# Environment Variables
env_variables:
  PYTHONUNBUFFERED: "1"
